### ISSUE TITLE
Network architecture

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/terraform-provider-iterative#123]
* [x] https://github.com/iterative/terraform-provider-iterative/issues/124
* [x] https://github.com/iterative/terraform-provider-iterative/issues/125
* [x] https://github.com/iterative/terraform-provider-iterative/issues/126
* [x] https://github.com/iterative/terraform-provider-iterative/issues/127

This is a really wide issue devised to track all the topics related to network architecture. Beware of [scope creep](https://en.wikipedia.org/wiki/Scope_creep) and [featuritis](https://en.wikipedia.org/wiki/Feature_creep)!

**Sources**

* [Slack / #cml / 1617986382008900](https://iterativeai.slack.com/archives/C01900GSB4J/p1617986382008900)
* [Slack / #cml / 1622727954276900](https://iterativeai.slack.com/archives/C01900GSB4J/p1622727954276900)
* https://github.com/iterative/cml/issues/377
* https://github.com/iterative/cml/issues/436
* https://github.com/iterative/cml/issues/439
* https://github.com/iterative/cml/issues/561
* https://github.com/iterative/terraform-provider-iterative/issues/107

**Comment by DavidGOrtega** [comment]
> Beware of scope creep and featuritis!

We just need a simply network def and a wrapper on top of the vendors what could be wrong... 😅

**Comment by 0x2b3bfa0** [comment]
What could possibly go wrong? 😅  Let's discuss the implementation details as soon as it's opportune.

**Comment by 0x2b3bfa0** [comment]
Closed with #237
