### ISSUE TITLE
task resource follow-up

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/terraform-provider-iterative#258]
_Note: this issue is not intended to track **completion** of the items, but rather its extraction to separate issues._

#### Documentation
* [x] **clarify `directory` and `shared` wording** #340
* [x] #267
* [x] #268
* [x] ~[consider collapsing `machine`, `region` and `image` sections](https://github.com/iterative/terraform-provider-iterative/pull/237#discussion_r749081767)~ moved to #363
* [x] ~[show examples for all the `task` resource arguments](https://github.com/iterative/terraform-provider-iterative/pull/237#discussion_r749781136)~ moved to #363

#### Code

* [x] https://github.com/iterative/terraform-provider-iterative/issues/287

#### Nitpicks

* [x] <s><kbd>p3-graveyard</kbd> Migrate GCP API to https://github.com/googleapis/google-cloud-go</s>

#### Others
These suggestions don't feel quite right given the current status of the project, but may eventually be addressed after evaluating the need of having separate `machine` and `task` resources.
* [x] https://github.com/iterative/terraform-provider-iterative/pull/237#discussion_r749554160, **share deterministic SSH logic with the `machine` resource**
* [x] https://github.com/iterative/terraform-provider-iterative/pull/237#discussion_r748323254, **share `diagnostics` helper function with `machine` resource**

**Comment by dacbd** [comment]
Might add a documentation footnote that after the `task` completes its instance is auto destroyed. I found this initially disorienting because of the terminology of terraform ie destroy

**Comment by 0x2b3bfa0** [comment]
<details>

![Captura de pantalla 2021-11-24 a las 0 55 43](https://user-images.githubusercontent.com/11387611/143147152-d3c3592c-3379-4207-a57d-6396995c6ae4.png)

[From Miro](https://miro.com/welcomeonboard/WDdXNWhhVXM0d1JBVkhYbEZjZGRJUnBsOFN2YVhkM29YQ3NGY[…]NGdMSFdvRXwzMDc0NDU3MzYwOTUxODk1MzM0?invite_link_id=598090150062)

</details>

**Comment by 0x2b3bfa0** [comment]
Closing in favor of #363

**Comment by 0x2b3bfa0** [comment]
The following nitpicks are irrelevant enough to be ignored for now:

* [ ] <kbd>p2-nice-to-have</kbd> Escape `rclone` connection strings properly https://github.com/rclone/rclone/issues/4996#issuecomment-778628943
* [ ] <kbd>p2-nice-to-have</kbd> Refactor orchestrator events & status as separate data sources
* [ ] <kbd>p2-nice-to-have</kbd> Chain attributes read to the outer task structs with pointers
* [ ] <kbd>p2-nice-to-have</kbd> Use https://github.com/openlyinc/pointy on every provider
* [ ] <kbd>p2-nice-to-have</kbd> Rename regions to locations so it's valid for zones and node selectors

**Comment by casperdcl** [comment]
@0x2b3bfa0 are those mentioned in another open issue? Would be good to keep track of them.

**Comment by 0x2b3bfa0** [comment]
No, they aren't. I'm hesitant to leave this issue open only for these nitpicks, create a new one, or let them be for now. I'm going to reopen this issue to avoid losing them in the backlog.

**Comment by casperdcl** [comment]
moved to #412

**Comment by 0x2b3bfa0** [comment]
Thanks!
