### ISSUE TITLE
docs: `task` requirements

### ISSUE THREAD

**Issue by casperdcl** [iterative/terraform-provider-iterative#363]
- [ ] where do env vars in https://registry.terraform.io/providers/iterative/iterative/latest/docs#authentication come from?
- [ ] what permissions are required (e.g. port 22 open)?
- [ ] improve formatting of table at https://registry.terraform.io/providers/iterative/iterative/latest/docs/guides/generic-machine-types

**Comment by 0x2b3bfa0** [comment]
> _This is not true at current status unless you use runner_<sup>[citation needed]</sup>

As far as I can tell, `iterative_task` terminates all the instances as soon as the `script` finishes running. 🤔

**Comment by 0x2b3bfa0** [comment]
Add to the list https://github.com/iterative/terraform-provider-iterative/issues/258#issuecomment-977180443, _“add a documentation footnote that after the task completes its instance is auto destroyed”_

**Comment by casperdcl** [comment]
Added an item to the `p1` checklist here instead :)

**Comment by DavidGOrtega** [comment]
@casperdcl can you please add these two?

 - [ ] Complete spot instances survival lifecycle (which is the best effort in tpi)
 - [ ] CI restart workflow lifecycle and explain also the environment propagation

**Comment by omesser** [comment]
@casperdcl  - suggest to add here the fix to the banner being broken [here](https://registry.terraform.io/providers/iterative/iterative/latest/docs)
Missing `banner-terraform.png`

**Comment by casperdcl** [comment]
thx added to #450 :)

**Comment by 0x2b3bfa0** [comment]
Don't forget this pearl:
* https://github.com/iterative/terraform-provider-iterative/issues/457#issuecomment-1076551061

      curl https://github.com/$GITHUB_ACTOR.keys >> $HOME/.ssh/authorized_keys

**Comment by casperdcl** [comment]
Already done https://registry.terraform.io/providers/iterative/iterative/latest/docs/guides/getting-started#debugging

**Comment by 0x2b3bfa0** [comment]
🙈 The sad part is that I reviewed that change.
