### ISSUE TITLE
task feedback 2

### ISSUE THREAD

**Issue by casperdcl** [iterative/terraform-provider-iterative#457]
Collecting feedback (may be moved elsewhere in future)

## p1

- [x] #452
- [x] @DavidGOrtega #477
  + [x] UX: `apply` fails ungracefully when spot pricing is too low? (might be solved by `TF_LOG_PROVIDER=INFO` in this list below)
    * if `0<spot` then `INFO: auto-pricing (spot=0) is recommended`
    * if `0<spot<0.10` then `WARN: spot=${spot}: maximum price probably too low. Try auto (0) or higher (>1)`
  + [x] CLI UX/docs
    * clearly warn about how long it can take to provision (`apply`)
    * clearly warn about how long it can take to clean up (`destroy`)
  + [x] @0x2b3bfa0 #462
- [x] @0x2b3bfa0 https://github.com/iterative/terraform-provider-iterative/pull/463
  - [x] @0x2b3bfa0 CLI UX/docs: clearly warn about large `workdir` uploads
  - [x] @0x2b3bfa0 CLI UX/docs: clearly warn about large `output` downloads
- [x] @0x2b3bfa0 & @casperdcl https://github.com/iterative/terraform-provider-iterative/pull/475
  + [x] docs: [clearly hint at utility of name/ID to find corresponding resources](https://github.com/iterative/terraform-provider-iterative/issues/457#issuecomment-1076565794) in the cloud console
  + [x] also, how does terraform `name` translate into cloud `ID? [don't actually recommend using it!](https://github.com/iterative/terraform-provider-iterative/issues/457#issuecomment-1076569501)
- [x] @casperdcl #450
  + [x] docs: fix registry banner
  + [x] docs: `TF_LOG_PROVIDER=INFO`, `DEBUG`, etc.
  + [x] docs: how to have long-running tasks (e.g. script deliberately `sleep`s)? Need bigger `timeout`?
  + [x] docs: how to debug ([using `trap`/`sleep` & SSH on failure](https://github.com/iterative/terraform-provider-iterative/issues/457#issuecomment-1076521349) with [`ssh_private_key`](https://registry.terraform.io/providers/iterative/iterative/latest/docs/resources/task#ssh_private_key) / [`addresses`](https://registry.terraform.io/providers/iterative/iterative/latest/docs/resources/task#addresses) / `echo "$(curl https://github.com/${GITHUB_USER}.keys)" >> $HOME/.ssh/authorized_keys`)?
  + [x] docs: [clarify `timeout`.](https://github.com/iterative/terraform-provider-iterative/issues/457#issuecomment-1079816091) "Run the given script on the cloud machine until completion or timeout" vs "Maximum number of seconds to run before termination" vs "# max 1h idle" - so does it apply to active time, idle time, or sum of both?

## p2

(moved to #363)

**Comment by 0x2b3bfa0** [comment]
> _feat: how to SSH for debugging?_

Did you mean `docs:` instead? 😄 See also [`ssh_private_key`](https://registry.terraform.io/providers/iterative/iterative/latest/docs/resources/task#ssh_private_key) and [`addresses`](https://registry.terraform.io/providers/iterative/iterative/latest/docs/resources/task#addresses)

**Comment by 0x2b3bfa0** [comment]
> _feat/docs: how to sleep & SSH on failure?_

`trap 'echo use SSH for debugging; sleep infinity' EXIT` in the first line?

**Comment by 0x2b3bfa0** [comment]
> _how to have long-running tasks (e.g. script deliberately sleeps)?_

* `script = "#!/bin/sh\nsleep infinity"` to run forever
* `script = "#!/bin/sh\nsleep 500"` to run for 5 minutes

**Comment by dacbd** [comment]
> > _feat: how to SSH for debugging?_
> 
> Did you mean `docs:` instead? 😄 See also [`ssh_private_key`](https://registry.terraform.io/providers/iterative/iterative/latest/docs/resources/task#ssh_private_key) and [`addresses`](https://registry.terraform.io/providers/iterative/iterative/latest/docs/resources/task#addresses)

Personally, I would prefer to have an option to provide a public key that gets additionally added, not interfering with the existing mechanism.

It's not unreasonable to assume that a user wouldn't want to/or can't expose their commonly used private_key, to override those options. 

maybe an example in the docs for a onliner to the effect of `echo "$(curl https://github.com/dacbd.keys)" >> $HOME/.ssh/authorized_keys`

**Comment by 0x2b3bfa0** [comment]
> _docs: clearly hint at utility of name/ID to find corresponding resources in the cloud console_

Search for a log line like this when running `terraform` commands:
```
iterative_task.task: Refreshing state... [id=tpi-1mb61lbbee8oj-27liktpn-6bfaepcv]
```

All the cloud resources will have either `tpi-1mb61lbbee8oj-27liktpn-6bfaepcv` or `tpi-27liktpn6bfaepcv` in the `name` field. All the resource names are guaranteed to begin with the `tpi-` prefix.

**Comment by 0x2b3bfa0** [comment]
> _also, how does terraform name translate into cloud ID?_

Setting `name` is not recommended for mere mortals: it generates a deterministic identifier containing the normalized name; is useful for CI/CD use cases.

For example, setting `name = "Some%String"` will create an identifier similar to this: `tpi-some-string-544rzp33-mz35yb5z`

**Comment by 0x2b3bfa0** [comment]
> _It's not unreasonable to assume that a user wouldn't want to/or can't expose their commonly used private_key, to override those options._

Please note that [ssh_private_key](https://registry.terraform.io/providers/iterative/iterative/latest/docs/resources/task#ssh_private_key) contains an automatically generated private key meant to be used with `ssh -i`; it's not the user's private key.

> _maybe an example in the docs for a onliner to the effect of echo "$(curl https://github.com/dacbd.keys)" >> $HOME/.ssh/authorized_keys_

Documenting this (as part of the script) would be awesome! ❤️

**Comment by dacbd** [comment]
> Please note that [ssh_private_key](https://registry.terraform.io/providers/iterative/iterative/latest/docs/resources/task#ssh_private_key) contains an automatically generated private key meant to be used with `ssh -i`; it's not the user's private key.

Right 🤦 , I guess my point is that, since the question is: "How do I ssh to the instance for remote debugging?" Should you connect with the managed key or your own: Whats a better experience? something synonymous to `ssh -i $(cat tfstate | jq .blah.private_key) which_user@$(cat tfstate | jq blah.address)`,  add this `previous example` at the beginning of script so you can ssh to instance (being the easiest/most immediate solution?), or an option in the `.tf` `authorized_keys | user_keys = ["ssh-rsa ..."]` /thoughts?

**Comment by casperdcl** [comment]
small :small_red_triangle_down: can fit into medium :green_circle: yes.

Exposing the internal private key mechanism thing always felt odd to me, even if "just for debugging."

Uploading authorised public keys seems much more friendly.

**Comment by 0x2b3bfa0** [comment]
_apply fails ungracefully when spot pricing is too low?_

`terraform apply` doesn't (at least shouldn't) fail when users manually specify a price that's lower than the current bidding price.

Resources are created, except for the machines themselves, which will be created automatically if/when the bidding price drops below the threshold provided by users.

**Comment by 0x2b3bfa0** [comment]
> _docs: clarify timeout. "Run the given script on the cloud machine until completion or timeout" vs "Maximum number of seconds to run before termination" vs "# max 1h idle" - so does it apply to active time, idle time, or sum of both?_

Whatever happens first. Machines will be terminated when either (1) the script exits willfully or (2) `timeout` seconds pass since it started to run.

On machines, this timeout isn't global (i.e. since `apply` was run); instead, it [resets](https://github.com/iterative/terraform-provider-iterative/blob/81872fad90aacc6437512d091d06e2c2b9dc1a36/task/common/machine/script.go#L69) for every new spot instance. On `k8s` this timeout value is [global](https://github.com/iterative/terraform-provider-iterative/blob/81872fad90aacc6437512d091d06e2c2b9dc1a36/task/k8s/resources/resource_job.go#L209) and limits the total duraion of the task.

**Comment by DavidGOrtega** [comment]
> `terraform apply` doesn't (at least shouldn't) fail when users manually specify a price that's lower than the current bidding price.

Its not but timeout does and pretty savage indeed

**Comment by DavidGOrtega** [comment]
@casperdcl @0x2b3bfa0 are we attacking this all together right? Should we create small tasks and assign them?

**Comment by 0x2b3bfa0** [comment]
@casperdcl, any other items/questions I can be helpful with?

**Comment by casperdcl** [comment]
> any other items/questions I can be helpful with?

added you to one more item at the top of this issue :pray:

**Comment by DavidGOrtega** [comment]
Why is this marked? The issue is still open. I was yesterday working to reproduce it

<img width="586" alt="image" src="https://user-images.githubusercontent.com/414967/161004360-dfcf3e66-f6ea-44db-be7f-5e984fad3fa4.png">

**Comment by casperdcl** [comment]
Makes sense, we can unmark it. Not sure if it should be `p1` or `p2`. #477 is definitely `p1`.

**Comment by casperdcl** [comment]
closing as p1 all addressed, and p2 moved to #363
