### ISSUE TITLE
Standalone command-line tool follow-up

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/terraform-provider-iterative#620]
Continuation of https://github.com/iterative/terraform-provider-iterative/pull/610

* [x] https://github.com/iterative/terraform-provider-iterative/issues/638
* [x] #652
* [x] #655
  * [x] Provide sensible logger output for TTY and non-TTY formats
  * [x] Separate commands to list logs & general status[^2]

[^1]: Unlike in Terraform HCL, values must not contain arithmetic expressions (e.g. `60*60*24` is not valid, but `86400` is valid). Also, declaring multiple `resource` blocks produces undefined behavior; i.e. defined behavior, but too contrived to explain in a footnote; definitely not what users expect.
[^2]: With a special case for $parallelism > 1$ where users can filter logs for a single task.

**Comment by dacbd** [comment]
after a "Provide sensible logger output for TTY and non-TTY formats" I think an `attach` type command would be helpful to "live" monitor a task.

**Comment by 0x2b3bfa0** [comment]
Part of _“Separate commands to list logs & general status”_ to my mind. It could be `log --follow` or similar?

**Comment by 0x2b3bfa0** [comment]
Closing in favor of https://github.com/iterative/terraform-provider-iterative/issues/666, which holds the remaining items 😈
